# Generated by Django 2.2 on 2021-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'ФИО',
                'verbose_name_plural': 'ФИО',
            },
        ),
    ]
